# Generated by Django 4.0.2 on 2022-02-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=50)),
                ('kid_age', models.IntegerField(max_length=3)),
                ('parent_ph_number', models.CharField(max_length=12)),
                ('parent_email_address', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField()),
                ('food_group', models.CharField(choices=[('veg', 'veg'), ('fruit', 'fruit'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Confectionery', 'Confectionery'), ('Unknown', 'Unknown')], max_length=100)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.kid')),
            ],
        ),
    ]
