# Generated by Django 4.0.2 on 2022-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_age',
            field=models.IntegerField(),
        ),
    ]
